FROM postgres:latest

# Definir variáveis de ambiente do banco de dados
ENV POSTGRES_DB=catalog
ENV POSTGRES_USER=mscott
ENV POSTGRES_PASSWORD=mscott

# Criar diretório para os scripts SQL
RUN mkdir -p /docker-entrypoint-initdb.d

# Copiar os scripts SQL para o container
COPY src/database/create.sql /docker-entrypoint-initdb.d/
COPY src/database/insert.sql /docker-entrypoint-initdb.d/

# Expor a porta padrão do PostgreSQL
EXPOSE 5432
