services:

  database:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.database
    container_name: database
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - catalog_network

  backend:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.backend
    container_name: backend
    expose:
      - 5000
    ports:
      - 5000:5000
    networks:
      - catalog_network
    depends_on:
      - database

  frontend:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.frontend
    container_name: frontend
    expose:
      - 8080
    ports:
      - 8080:80
    networks:
      - catalog_network
    depends_on:
      - backend

networks:
  catalog_network:
    driver: bridge
