INSERT INTO Category (Id, Name, Description, Active, CreatedAt, UpdatedAt) VALUES
(1, 'Pens', 'Various types of pens for writing.', true, NOW(), NOW()),
(2, 'Pencils', 'Writing pencils and colored pencils.', true, NOW(), NOW()),
(3, 'Notebooks', 'Notebooks of different sizes and styles.', true, NOW(), NOW()),
(4, 'Erasers', 'Erasers for erasing pencils and pens.', true, NOW(), NOW()),
(5, 'Markers', 'Highlighters and permanent markers.', true, NOW(), NOW()),
(6, 'Planners', 'Planners for planning and organizing.', true, NOW(), NOW()),
(7, 'Papers', 'Papers of different weights and textures.', true, NOW(), NOW()),
(8, 'Staplers', 'Staplers for attaching sheets of paper.', true, NOW(), NOW()),
(9, 'Scissors', 'Scissors for cutting paper and materials.', true, NOW(), NOW()),
(10, 'Organizers', 'Organizers for office and stationery.', true, NOW(), NOW());

INSERT INTO Product (Id, Name, Description, Brand, Model, Price, Stock, Active, CreatedAt, UpdatedAt, CategoryId) VALUES
(1, 'Ballpoint Pen', 'Black ballpoint pen for everyday writing tasks.', 'Bic', 'Cristal', 1.99, 12, true, NOW(), NOW(), 1),
(2, 'Gel Pen Set', 'Set of assorted gel pens in vibrant colors.', 'PaperMate', 'InkJoy Gel', 9.99, 44, true, NOW(), NOW(), 1),
(3, 'Fountain Pen', 'Classic fountain pen with refillable ink cartridge.', 'Parker', 'Sonnet', 49.99, 523, true, NOW(), NOW(), 1),
(4, 'Highlighter', 'Yellow highlighter marker for emphasizing text.', 'Sharpie', 'Accent', 1.49, 2, true, NOW(), NOW(), 1),
(5, 'Rollerball Pen', 'Smooth writing rollerball pen with fine tip.', 'Uni-ball', 'Vision Elite', 2.99, 42, true, NOW(), NOW(), 1),
(6, 'Mechanical Pencils', 'Pack of mechanical pencils with refillable lead.', 'Pentel', 'Sharp', 4.99, 8, true, NOW(), NOW(), 2),
(7, 'Wooden Pencils', 'Classic wooden pencils with eraser tips.', 'Dixon', 'Ticonderoga', 3.49, 645, true, NOW(), NOW(), 2),
(8, 'Colored Pencils', 'Set of vibrant colored pencils for artwork.', 'Prismacolor', 'Premier', 12.99, 234, true, NOW(), NOW(), 2),
(9, 'HB Pencils', 'Standard HB pencils for writing and sketching.', 'Faber-Castell', 'Goldfaber', 2.99, 34, true, NOW(), NOW(), 2),
(10, 'Mechanical Pencil Set', 'Set of mechanical pencils with assorted lead sizes.', 'Zebra', 'M-301', 7.99, 134, true, NOW(), NOW(), 2),
(11, 'College Ruled Notebook', 'Classic college-ruled notebook with wire binding.', 'Mead', 'Five Star', 6.99, 234, true, NOW(), NOW(), 3),
(12, 'Sketchbook', 'Hardcover sketchbook with acid-free paper.', 'Strathmore', '400 Series', 14.99, 345, true, NOW(), NOW(), 3),
(13, 'Composition Notebook', 'Standard composition notebook with sewn binding.', 'Roaring Spring', 'Wide Ruled', 2.99, 785, true, NOW(), NOW(), 3),
(14, 'Bullet Journal', 'Dotted bullet journal for creative planning.', 'Leuchtturm1917', 'A5 Hardcover', 19.99, 12, true, NOW(), NOW(), 3),
(15, 'Planner', 'Weekly planner with monthly overviews and goal-setting pages.', 'Blue Sky', 'Passages', 9.99, 234, true, NOW(), NOW(), 3),
(16, 'White Erasers', 'Soft white erasers for pencil marks.', 'PaperMate', 'Pink Pearl', 0.99, 76, true, NOW(), NOW(), 4),
(17, 'Kneaded Eraser', 'Kneaded eraser for graphite and charcoal.', 'Prismacolor', 'ArtGum', 1.99, 77, true, NOW(), NOW(), 4),
(18, 'Vinyl Erasers', 'Vinyl erasers for clean erasing.', 'Pentel', 'Hi-Polymer', 1.49, 34, true, NOW(), NOW(), 4),
(19, 'Electric Eraser', 'Battery-powered eraser for precise corrections.', 'Sakura', 'Electric Eraser', 9.99, 432, true, NOW(), NOW(), 4),
(20, 'Block Eraser', 'Large block eraser for heavy erasing.', 'Staedtler', 'Mars Plastic', 1.99, 66, true, NOW(), NOW(), 4),
(21, 'Permanent Markers', 'Set of permanent markers for labeling.', 'Sharpie', 'Fine Point', 7.99, 456, true, NOW(), NOW(), 5),
(22, 'Dry Erase Markers', 'Pack of dry erase markers for whiteboards.', 'Expo', 'Chisel Tip', 6.49, 12, true, NOW(), NOW(), 5),
(23, 'Highlighter Set', 'Assorted highlighter set in various colors.', 'Zebra', 'Mildliner', 11.99, 1, true, NOW(), NOW(), 5),
(24, 'Fabric Markers', 'Fabric markers for permanent textile designs.', 'Tulip', 'Dual-Tip', 8.99, 456, true, NOW(), NOW(), 5),
(25, 'Brush Markers', 'Brush tip markers for calligraphy and artwork.', 'Tombow', 'Dual Brush', 24.99, 86, true, NOW(), NOW(), 5),
(26, 'Daily Planner', 'Daily planner with hourly schedule and to-do lists.', 'Day Designer', 'The Original', 29.99, 543, true, NOW(), NOW(), 6),
(27, 'Weekly Planner', 'Weekly planner with goal-setting pages and habit trackers.', 'Passion Planner', 'Classic', 24.99, 76, true, NOW(), NOW(), 6),
(28, 'Monthly Planner', 'Monthly planner with spacious calendar pages.', 'Blue Sky', 'Day Designer', 14.99, 345, true, NOW(), NOW(), 6),
(29, 'Academic Planner', 'Academic year planner with school-specific features.', 'Mead', 'Five Star', 12.99, 765, true, NOW(), NOW(), 6),
(30, 'Goal Setting Journal', 'Goal-setting journal for personal and professional growth.', 'BestSelf', 'Self Journal', 29.99, 56, true, NOW(), NOW(), 6);
